# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Lasttask4.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtCore import Qt
import cv2
import numpy as np
from PyQt5.QtWidgets import QApplication
from PyQt5.QtCore import QTimer
import sys
from functools import partial




class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(968, 719)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.FT_component_1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.FT_component_1.setObjectName("FT_component_1")
        self.gridLayout.addWidget(self.FT_component_1, 1, 0, 1, 1)
        self.output_3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.output_3.setObjectName("output_3")
        self.gridLayout.addWidget(self.output_3, 3, 1, 3, 1)
        self.FT_component_4 = QtWidgets.QGraphicsView(self.centralwidget)
        self.FT_component_4.setObjectName("FT_component_4")
        self.gridLayout.addWidget(self.FT_component_4, 1, 3, 1, 1)
        self.image_4 = QtWidgets.QGraphicsView(self.centralwidget)
        self.image_4.setObjectName("image_4")
        self.gridLayout.addWidget(self.image_4, 0, 3, 1, 1)
        self.image_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.image_2.setObjectName("image_2")
        self.gridLayout.addWidget(self.image_2, 0, 1, 1, 1)
        self.FT_component_3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.FT_component_3.setObjectName("FT_component_3")
        self.gridLayout.addWidget(self.FT_component_3, 1, 2, 1, 1)
        self.output_4 = QtWidgets.QGraphicsView(self.centralwidget)
        self.output_4.setObjectName("output_4")
        self.gridLayout.addWidget(self.output_4, 3, 0, 3, 1)
        self.image_1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.image_1.setObjectName("image_1")
        self.gridLayout.addWidget(self.image_1, 0, 0, 1, 1)
        self.FT_component_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.FT_component_2.setObjectName("FT_component_2")
        self.gridLayout.addWidget(self.FT_component_2, 1, 1, 1, 1)
        self.image_3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.image_3.setObjectName("image_3")
        self.gridLayout.addWidget(self.image_3, 0, 2, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 1)
        self.component_1_combobox = QtWidgets.QComboBox(self.frame)
        self.component_1_combobox.setObjectName("component_1_combobox")
        self.gridLayout_2.addWidget(self.component_1_combobox, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 3, 1, 1)
        self.component_2_combobox = QtWidgets.QComboBox(self.frame)
        self.component_2_combobox.setObjectName("component_2_combobox")
        self.gridLayout_2.addWidget(self.component_2_combobox, 0, 4, 1, 1)
        self.component_1_slider = QtWidgets.QSlider(self.frame)
        self.component_1_slider.setOrientation(QtCore.Qt.Horizontal)
        self.component_1_slider.setObjectName("component_1_slider")
        self.gridLayout_2.addWidget(self.component_1_slider, 1, 0, 1, 2)
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout_2.addWidget(self.lcdNumber, 1, 2, 1, 1)
        self.component_2_slider = QtWidgets.QSlider(self.frame)
        self.component_2_slider.setOrientation(QtCore.Qt.Horizontal)
        self.component_2_slider.setObjectName("component_2_slider")
        self.gridLayout_2.addWidget(self.component_2_slider, 1, 3, 1, 2)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout_2.addWidget(self.lcdNumber_2, 1, 5, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 2, 0, 1, 1)
        self.component_3_combobox = QtWidgets.QComboBox(self.frame)
        self.component_3_combobox.setObjectName("component_3_combobox")
        self.gridLayout_2.addWidget(self.component_3_combobox, 2, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 2, 3, 1, 1)
        self.component_4_combobox = QtWidgets.QComboBox(self.frame)
        self.component_4_combobox.setObjectName("component_4_combobox")
        self.gridLayout_2.addWidget(self.component_4_combobox, 2, 4, 1, 1)
        self.component_3_slider = QtWidgets.QSlider(self.frame)
        self.component_3_slider.setOrientation(QtCore.Qt.Horizontal)
        self.component_3_slider.setObjectName("component_3_slider")
        self.gridLayout_2.addWidget(self.component_3_slider, 3, 0, 1, 2)
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.gridLayout_2.addWidget(self.lcdNumber_3, 3, 2, 1, 1)
        self.component_4_slider = QtWidgets.QSlider(self.frame)
        self.component_4_slider.setOrientation(QtCore.Qt.Horizontal)
        self.component_4_slider.setObjectName("component_4_slider")
        self.gridLayout_2.addWidget(self.component_4_slider, 3, 3, 1, 2)
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.gridLayout_2.addWidget(self.lcdNumber_4, 3, 5, 1, 1)
        self.gridLayout.addWidget(self.frame, 2, 2, 2, 2)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Magnitude_phase_radiobutto = QtWidgets.QRadioButton(self.frame_3)
        self.Magnitude_phase_radiobutto.setObjectName("Magnitude_phase_radiobutto")
        self.gridLayout_3.addWidget(self.Magnitude_phase_radiobutto, 0, 0, 1, 1)
        self.Real_imaginary_radiobutton = QtWidgets.QRadioButton(self.frame_3)
        self.Real_imaginary_radiobutton.setObjectName("Real_imaginary_radiobutton")
        self.gridLayout_3.addWidget(self.Real_imaginary_radiobutton, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 4, 2, 1, 2)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 0, 0, 1, 1)
        self.image_no_combobox = QtWidgets.QComboBox(self.frame_2)
        self.image_no_combobox.setObjectName("image_no_combobox")
        self.gridLayout_4.addWidget(self.image_no_combobox, 0, 1, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 3, 1, 1)
        self.components_combobox = QtWidgets.QComboBox(self.frame_2)
        self.components_combobox.setObjectName("components_combobox")
        self.gridLayout_4.addWidget(self.components_combobox, 0, 4, 1, 1)
        self.inner_region_radiobutton = QtWidgets.QRadioButton(self.frame_2)
        self.inner_region_radiobutton.setObjectName("inner_region_radiobutton")
        self.gridLayout_4.addWidget(self.inner_region_radiobutton, 1, 0, 1, 2)
        self.outer_region_radiobutton = QtWidgets.QRadioButton(self.frame_2)
        self.outer_region_radiobutton.setObjectName("outer_region_radiobutton")
        self.gridLayout_4.addWidget(self.outer_region_radiobutton, 1, 2, 1, 1)
        self.Regions = QtWidgets.QLabel(self.frame_2)
        self.Regions.setStyleSheet("\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.Regions.setObjectName("Regions")
        self.gridLayout_4.addWidget(self.Regions, 1, 3, 1, 1)
        self.region_slider = QtWidgets.QSlider(self.frame_2)
        self.region_slider.setOrientation(QtCore.Qt.Horizontal)
        self.region_slider.setObjectName("region_slider")
        self.gridLayout_4.addWidget(self.region_slider, 1, 4, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 2, 0, 1, 2)
        self.frame_outputs_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_outputs_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_outputs_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_outputs_2.setObjectName("frame_outputs_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_outputs_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton = QtWidgets.QPushButton(self.frame_outputs_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_5.addWidget(self.pushButton, 0, 0, 1, 2)
        self.regions_mixing_button = QtWidgets.QPushButton(self.frame_outputs_2)
        self.regions_mixing_button.setObjectName("regions_mixing_button")
        self.gridLayout_5.addWidget(self.regions_mixing_button, 0, 2, 1, 1)
        self.Stop_mixing_button = QtWidgets.QPushButton(self.frame_outputs_2)
        self.Stop_mixing_button.setObjectName("Stop_mixing_button")
        self.gridLayout_5.addWidget(self.Stop_mixing_button, 0, 3, 1, 1)
        self.output_1_radioButton = QtWidgets.QRadioButton(self.frame_outputs_2)
        self.output_1_radioButton.setObjectName("output_1_radioButton")
        self.gridLayout_5.addWidget(self.output_1_radioButton, 1, 0, 1, 1)
        self.output_2_radioButton = QtWidgets.QRadioButton(self.frame_outputs_2)
        self.output_2_radioButton.setObjectName("output_2_radioButton")
        self.gridLayout_5.addWidget(self.output_2_radioButton, 1, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.frame_outputs_2)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_5.addWidget(self.progressBar, 1, 2, 1, 2)
        self.gridLayout.addWidget(self.frame_outputs_2, 5, 2, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.MainWindow = MainWindow

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_13.setText(_translate("MainWindow", "Component 1"))
        self.label_15.setText(_translate("MainWindow", "Component 2"))
        self.label_16.setText(_translate("MainWindow", "Component 3"))
        self.label_17.setText(_translate("MainWindow", "Component 4"))
        self.Magnitude_phase_radiobutto.setText(_translate("MainWindow", "Magnitude and Phase "))
        self.Real_imaginary_radiobutton.setText(_translate("MainWindow", "Real and Imaginary"))
        self.label_10.setText(_translate("MainWindow", "Image Number"))
        self.label_9.setText(_translate("MainWindow", "FT Components"))
        self.inner_region_radiobutton.setText(_translate("MainWindow", "Inner region"))
        self.outer_region_radiobutton.setText(_translate("MainWindow", "Outer region"))
        self.Regions.setText(_translate("MainWindow", "Regions"))
        self.pushButton.setText(_translate("MainWindow", "Mix Components"))
        self.regions_mixing_button.setText(_translate("MainWindow", "Regions Mixing "))
        self.Stop_mixing_button.setText(_translate("MainWindow", "Stop Mixing "))
        self.output_1_radioButton.setText(_translate("MainWindow", "Output 1"))
        self.output_2_radioButton.setText(_translate("MainWindow", "Output 2"))

        
        # Connect double-click events to the image views
        self.image_1.mouseDoubleClickEvent = lambda event: self.browse_and_convert(event, self.image_1)
        self.image_2.mouseDoubleClickEvent = lambda event: self.browse_and_convert(event, self.image_2)
        self.image_3.mouseDoubleClickEvent = lambda event: self.browse_and_convert(event, self.image_3)
        self.image_4.mouseDoubleClickEvent = lambda event: self.browse_and_convert(event, self.image_4)

        # Connect the sliderReleased signal of sliders to corresponding slots
        self.component_1_slider.sliderReleased.connect(lambda: self.update_ft_component_slider(self.component_1_slider.value(), self.component_1_combobox, "Image 1"))
        self.component_2_slider.sliderReleased.connect(lambda: self.update_ft_component_slider(self.component_2_slider.value(), self.component_2_combobox, "Image 2"))
        self.component_3_slider.sliderReleased.connect(lambda: self.update_ft_component_slider(self.component_3_slider.value(), self.component_3_combobox, "Image 3"))
        self.component_4_slider.sliderReleased.connect(lambda: self.update_ft_component_slider(self.component_4_slider.value(), self.component_4_combobox, "Image 4"))

        # Connect the valueChanged signal of each slider to the corresponding LCD update function
        self.component_1_slider.valueChanged.connect(lambda value: self.update_lcd(self.lcdNumber, value))
        self.component_2_slider.valueChanged.connect(lambda value: self.update_lcd(self.lcdNumber_2, value))
        self.component_3_slider.valueChanged.connect(lambda value: self.update_lcd(self.lcdNumber_3, value))
        self.component_4_slider.valueChanged.connect(lambda value: self.update_lcd(self.lcdNumber_4, value))

       
        self.pushButton.clicked.connect(self.mix_and_display)

        # Connect the slider's valueChanged signal to a slot (update_displayed_regions)
        self.region_slider.valueChanged.connect(self.extract_region)

        # Connect the regions_mixing_button click event to the handler
        self.regions_mixing_button.clicked.connect(self.mix_regions)

        self.pushButton.clicked.connect(self.button_clicked)
        self.regions_mixing_button.clicked.connect(self.button_clicked)

        self.Stop_mixing_button.clicked.connect(self.stop_mixing)

        # Connect the activated signal of components_combobox to the update_ft_components slot
        self.components_combobox.activated.connect(self.update_ft_components)

        # Connect signal for radio buttons
        self.Real_imaginary_radiobutton.toggled.connect(self.update_combobox_choices)
        self.Magnitude_phase_radiobutto.toggled.connect(self.update_combobox_choices)

        components_options = ["FT Magnitude", "FT Phase", "FT Real", "FT Imaginary"]
        self.components_combobox.addItems(components_options)
        
        Images_numbers = ["Image 1", "Image 2", "Image 3", "Image 4"]
        self.image_no_combobox.addItems(Images_numbers)

        # Add a dictionary to map image views to image names
        self.image_view_to_name = {
            self.image_1: "Image 1",
            self.image_2: "Image 2",
            self.image_3: "Image 3",
            self.image_4: "Image 4",
        }

        # Initialize the dictionary for storing Fourier transform data
        self.ft_component_data = {
            "Image 1": {"FT Magnitude": None, "FT Phase": None, "FT Real": None, "FT Imaginary": None},
            "Image 2": {"FT Magnitude": None, "FT Phase": None, "FT Real": None, "FT Imaginary": None},
            "Image 3": {"FT Magnitude": None, "FT Phase": None, "FT Real": None, "FT Imaginary": None},
            "Image 4": {"FT Magnitude": None, "FT Phase": None, "FT Real": None, "FT Imaginary": None}
        }


        # Initialize the dictionary for storing adjusted Fourier transform data
        self.adjusted_ft_data = {
            "Image 1": {"FT Magnitude": None, "FT Phase": None, "FT Real": None, "FT Imaginary": None},
            "Image 2": {"FT Magnitude": None, "FT Phase": None, "FT Real": None, "FT Imaginary": None},
            "Image 3": {"FT Magnitude": None, "FT Phase": None, "FT Real": None, "FT Imaginary": None},
            "Image 4": {"FT Magnitude": None, "FT Phase": None, "FT Real": None, "FT Imaginary": None}
        }

        self.summed_ft_data = {
            "Summed Magnitude": None,
            "Summed Phase": None,
            "Summed Real": None,
            "Summed Imaginary": None
        }

        self.ft_component_extracted_region = {
            "Image 1":  None,
            "Image 2":  None,
            "Image 3": None,
            "Image 4": None
        }

        self.original_extracted_region = {
            "Image 1": None,
            "Image 2": None,
            "Image 3": None,
            "Image 4": None
        }

        # Connect double-click events to the image views
        for image_view in [ self.image_1 ,self.image_2, self.image_3, self.image_4]:
            image_view.mouseDoubleClickEvent = partial(self.browse_and_convert, image_view=image_view)

            # Connect mouse press and move events to the image views
            image_view.mousePressEvent = partial(self.mouse_press_event, image_view=image_view)
            image_view.mouseMoveEvent = partial(self.mouse_move_event, image_view=image_view)

        
    def mouse_press_event(self, event, image_view):
        if event.button() == Qt.LeftButton:
            # Store the initial position for reference in mouse_move_event
            image_view.initial_pos = event.pos()

    def mouse_move_event(self, event, image_view):
        # Check if the left button is pressed and an initial position is stored
        if event.buttons() == Qt.LeftButton and hasattr(image_view, 'initial_pos'):
            # Calculate the vertical movement
            delta_y = event.pos().y() - image_view.initial_pos.y()

            # Calculate the horizontal movement
            delta_x = event.pos().x() - image_view.initial_pos.x()

            # Adjust the brightness based on the movement 
            brightness_adjustment = delta_y*5
            self.adjust_image_brightness(image_view, brightness_adjustment)

            # Adjust the contrast based on the movement 
            contrast_adjustment = delta_x
            self.adjust_image_contrast(image_view, contrast_adjustment)

    def adjust_image_contrast(self, image_view, contrast_adjustment):
        # Get the image name based on the image_view
        image_name = self.image_view_to_name.get(image_view, "Unknown Image")

        # Retrieve the time-domain data of the image
        time_domain_data = self.image_view_to_name.get(image_name)

        # Adjust the contrast of the image
        adjusted_image = self.modify_contrast(time_domain_data, contrast_adjustment)

     
        # Display the adjusted image in the QGraphicsView
        self.display_image_in_view(adjusted_image, image_view)

    def display_image_in_view(self, image, image_view):
        # Convert the image to QPixmap and scale it to fit within the QGraphicsView
        pixmap = QPixmap.fromImage(QImage(image.data, image.shape[1], image.shape[0], image.shape[1], QImage.Format_Grayscale8))
        scaled_pixmap = pixmap.scaled(image_view.width(), image_view.height(), Qt.KeepAspectRatio)

        # Update the QGraphicsView with the scaled image
        image_view.setSceneRect(0, 0, scaled_pixmap.width(), scaled_pixmap.height())
        image_view.setScene(QtWidgets.QGraphicsScene())
        image_view.scene().addPixmap(scaled_pixmap)

    def adjust_image_brightness(self, image_view, brightness_adjustment):
        # Get the image name based on the image_view
        image_name = self.image_view_to_name.get(image_view, "Unknown Image")

        # Retrieve the time-domain data of the image
        time_domain_data = self.image_view_to_name.get(image_name)

        # Adjust the brightness of the image
        adjusted_image = self.modify_brightness(time_domain_data, brightness_adjustment)



        # Display the adjusted image in the QGraphicsView
        self.display_image_in_view(adjusted_image, image_view)

    def modify_contrast(self, image, adjustment):
        # Perform contrast adjustment on the image
        alpha = 1.0 + adjustment / 100.0
        adjusted_image = cv2.multiply(image, alpha)

        # Ensure pixel values are within the valid range
        adjusted_image = np.clip(adjusted_image, 0, 255)

        return adjusted_image

    def modify_brightness(self, image, adjustment):
        # Perform brightness adjustment on the image
        adjusted_image = cv2.addWeighted(image, 1, np.zeros_like(image), 0, adjustment)

        # Ensure pixel values are within the valid range
        adjusted_image = np.clip(adjusted_image, 0, 255)

        return adjusted_image
    
    def browse_and_convert(self, event, image_view):
        if event.button() == Qt.LeftButton and event.modifiers() == Qt.NoModifier:
            file_dialog = QFileDialog()
            file_dialog.setNameFilter("Images (*.png *.xpm *.jpg *.bmp)")
            file_dialog.setViewMode(QFileDialog.Detail)
            
            if file_dialog.exec_():
                file_path = file_dialog.selectedFiles()[0]
                
                # Read the time-domain data of the image
                time_domain_data = self.read_image_data(file_path)

                # Determine the image name based on the image_view
                image_name = self.image_view_to_name.get(image_view, "Unknown Image")
                self.image_view_to_name[image_name] = time_domain_data

                # Print the contents of the image_data dictionary
                # print("image data:", self.image_view_to_name)  

                # Calculate Fourier transform data
                ft_magnitude, ft_phase, ft_real, ft_imaginary = self.calculate_fourier_transform(time_domain_data)

                # Update the dictionary with Fourier transform data
                self.ft_component_data[image_name]["FT Magnitude"] = ft_magnitude
                self.ft_component_data[image_name]["FT Phase"] = ft_phase
                self.ft_component_data[image_name]["FT Real"] = ft_real
                self.ft_component_data[image_name]["FT Imaginary"] = ft_imaginary
                

                # Print the contents of the ft_component_data dictionary
                # print("FT component data:", self.ft_component_data)  

                image = QPixmap(file_path).toImage().convertToFormat(QImage.Format_Grayscale8)
                
                # Scale the image to fit within the QGraphicsView
                scaled_image = image.scaled(image_view.width(), image_view.height(), Qt.KeepAspectRatio)

                image_view.setSceneRect(0, 0, scaled_image.width(), scaled_image.height())
                image_view.setScene(QtWidgets.QGraphicsScene())
                image_view.scene().addPixmap(QPixmap.fromImage(scaled_image))

    def read_image_data(self, file_path):
        # Read the image using OpenCV
        original_image = cv2.imread(file_path, cv2.IMREAD_GRAYSCALE)

        # Resize the image to a fixed size (e.g., 200x200 pixels)
        resized_image = cv2.resize(original_image, (200, 200))

        return resized_image
       
    def calculate_fourier_transform(self, time_domain_data):
        # Compute the discrete Fourier Transform of the image
        fourier = np.fft.fft2(time_domain_data)

        # Shift the zero-frequency component to the center of the spectrum
        fourier_shift = np.fft.fftshift(fourier)

        # Calculate the magnitude of the Fourier Transform
        ft_magnitude = np.abs(fourier_shift)
       
        # Calculate the phase of the Fourier Transform
        ft_phase = np.angle(fourier_shift)

        # Calculate the real part of the Fourier Transform
        ft_real = np.real(fourier_shift)

        # Calculate the imaginary part of the Fourier Transform
        ft_imaginary = np.imag(fourier_shift)

        return ft_magnitude, ft_phase, ft_real, ft_imaginary

    def update_ft_components(self):
        # Get the selected image name and Fourier component from the comboboxes
        selected_image = self.image_no_combobox.currentText()
        selected_component = self.components_combobox.currentText()

        # Retrieve the corresponding Fourier component data from the dictionary
        ft_component_data = self.ft_component_data.get(selected_image, {})
        ft_data = ft_component_data.get(selected_component, None)

        # Save the inner region in the ft_component_extracted_region dictionary
        self.original_extracted_region[selected_image] = ft_data


        if "FT Magnitude" == self.components_combobox.currentText() :
                # Apply logarithmic transformation to the magnitude
                ft_data = 20 * np.log(np.abs(ft_data))

        # Update the FT_component graphics view based on the selected image number
        if selected_image == "Image 1":
            self.display_ft_component(ft_data, self.FT_component_1)
        elif selected_image == "Image 2":
            self.display_ft_component(ft_data, self.FT_component_2)
        elif selected_image == "Image 3":
            self.display_ft_component(ft_data, self.FT_component_3)
        elif selected_image == "Image 4":
            self.display_ft_component(ft_data, self.FT_component_4)

    def display_ft_component(self, ft_data, ft_graphics_view):
        # Check if Fourier component data is available
        if ft_data is not None:
            
            # Normalize data to the range [0, 255]
            ft_data_normalized = cv2.normalize(ft_data, None, 0, 255, cv2.NORM_MINMAX, cv2.CV_8UC1)

            # Create QImage from the Fourier component data
            height, width = ft_data_normalized.shape[:2]
            q_image = QImage(ft_data_normalized.data, width, height, ft_data_normalized.strides[0], QImage.Format_Grayscale8)

            # Convert QImage to QPixmap
            q_pixmap = QPixmap.fromImage(q_image)

            # Scale the image to fit within the QGraphicsView
            scaled_ft_pixmap = q_pixmap.scaled(ft_graphics_view.width(), ft_graphics_view.height(), Qt.KeepAspectRatio)

            # Display the Fourier component in the QGraphicsView
            ft_graphics_view.setSceneRect(0, 0, scaled_ft_pixmap.width(), scaled_ft_pixmap.height())
            ft_graphics_view.setScene(QtWidgets.QGraphicsScene())
            ft_graphics_view.scene().addPixmap(scaled_ft_pixmap)
        else:
            # Clear the QGraphicsView if Fourier component data is not available
            ft_graphics_view.setSceneRect(0, 0, 0, 0)
            ft_graphics_view.setScene(QtWidgets.QGraphicsScene())

    def update_combobox_choices(self):
        if self.Real_imaginary_radiobutton.isChecked():
            # Real and Imaginary components
            component_choices = ["FT Real", "FT Imaginary"]
        elif self.Magnitude_phase_radiobutto.isChecked():
            # Magnitude and Phase components
            component_choices = ["FT Magnitude", "FT Phase"]
        else:
            # Default choices
            component_choices = []

        # Update combobox choices for all four components
        for combobox in [self.component_1_combobox, self.component_2_combobox, self.component_3_combobox, self.component_4_combobox]:
            combobox.clear()
            combobox.addItems(component_choices)   

    def update_ft_component_slider(self, slider_value, combobox, image_name):
        # Get the selected component from the combobox
        selected_component = combobox.currentText()

        # Retrieve the corresponding Fourier component data from the dictionary
        ft_component_data = self.ft_component_data.get(image_name, {})
        ft_data = ft_component_data.get(selected_component, None)

        if ft_data is not None:
            # Apply the slider value as a percentage of the max value to all components
            slider_percentage = slider_value / max(self.component_1_slider.maximum(), self.component_2_slider.maximum(),
                                                self.component_3_slider.maximum(), self.component_4_slider.maximum())
            adjusted_ft_data = {key: value * slider_percentage if key == selected_component else None for key, value in ft_component_data.items()}

            # Fill None values with zeros
            adjusted_ft_data = {key: value if value is not None else np.zeros_like(ft_component_data[selected_component]) for key, value in adjusted_ft_data.items()}

            # Save the adjusted array in a new dictionary
            self.adjusted_ft_data[image_name] = adjusted_ft_data

            # Sum the available data and update the summed_ft_data dictionary
            for name, data in self.adjusted_ft_data.items():
                if data["FT Magnitude"] is not None:
                    self.summed_ft_data["Summed Magnitude"] = data["FT Magnitude"]
                if data["FT Phase"] is not None:
                    self.summed_ft_data["Summed Phase"] = data["FT Phase"]
                if data["FT Real"] is not None:
                    self.summed_ft_data["Summed Real"] = data["FT Real"]
                if data["FT Imaginary"] is not None:
                    self.summed_ft_data["Summed Imaginary"] = data["FT Imaginary"]

            # Create new arrays to store summed data
        summed_magnitude = np.zeros_like(ft_component_data["FT Magnitude"])
        summed_phase = np.zeros_like(ft_component_data["FT Phase"])
        summed_real = np.zeros_like(ft_component_data["FT Real"])
        summed_imaginary = np.zeros_like(ft_component_data["FT Imaginary"])

        for name, data in self.adjusted_ft_data.items():
            if data["FT Magnitude"] is not None:
                summed_magnitude += data["FT Magnitude"]

            if data["FT Phase"] is not None:
                summed_phase += data["FT Phase"]

            if data["FT Real"] is not None:
                summed_real += data["FT Real"]

            if data["FT Imaginary"] is not None:
                summed_imaginary += data["FT Imaginary"]

        # Update the summed_ft_data dictionary with the accumulated values
        self.summed_ft_data = {
            "Summed Magnitude": summed_magnitude,
            "Summed Phase": summed_phase,
            "Summed Real": summed_real,
            "Summed Imaginary": summed_imaginary,
        }
        # Print the contents of the summed_ft_data dictionary
        # print("Summed FT component data:", self.summed_ft_data)

    def display_time_domain_image(self, time_domain_data, is_output_1):
        # Normalize the time domain data to the range [0, 255]
        time_domain_data_normalized = cv2.normalize(time_domain_data, None, 0, 255, cv2.NORM_MINMAX, cv2.CV_8UC1)

        # Create QImage from the time domain data
        height, width = time_domain_data_normalized.shape[:2]
        q_image = QImage(time_domain_data_normalized.data, width, height, time_domain_data_normalized.strides[0], QImage.Format_Grayscale8)

        # Convert QImage to QPixmap
        q_pixmap = QPixmap.fromImage(q_image)

        # Scale the image to fit within the QGraphicsView
        scaled_time_domain_pixmap = q_pixmap.scaled(self.output_3.width(), self.output_3.height(), Qt.KeepAspectRatio)

        # Display the time domain image in the QGraphicsView
        if is_output_1:
            self.output_3.setSceneRect(0, 0, scaled_time_domain_pixmap.width(), scaled_time_domain_pixmap.height())
            self.output_3.setScene(QtWidgets.QGraphicsScene())
            self.output_3.scene().addPixmap(scaled_time_domain_pixmap)
        else:
            self.output_4.setSceneRect(0, 0, scaled_time_domain_pixmap.width(), scaled_time_domain_pixmap.height())
            self.output_4.setScene(QtWidgets.QGraphicsScene())
            self.output_4.scene().addPixmap(scaled_time_domain_pixmap)

    def mix_and_display(self):
        # Check if the Magnitude and Phase radio button is checked
        if self.Magnitude_phase_radiobutto.isChecked():
            # Check if the Magnitude and Phase components are available in summed_ft_data
            if "Summed Magnitude" in self.summed_ft_data and "Summed Phase" in self.summed_ft_data:
                # Mix the Magnitude and Phase components
                mixed_ft_data = self.summed_ft_data["Summed Magnitude"] * np.exp(1j * self.summed_ft_data["Summed Phase"])

                # Perform inverse Fourier transform
                mixed_time_domain_data = np.fft.ifft2(np.fft.ifftshift(mixed_ft_data)).real

                # Display the mixed time domain data as an image
                self.display_time_domain_image(mixed_time_domain_data, self.output_1_radioButton.isChecked())
            else:
                print("Error: Magnitude and Phase components are not available for mixing.")

    
        # Check if the Magnitude and Phase radio button is checked
        if self.Real_imaginary_radiobutton.isChecked():
            # Check if the Magnitude and Phase components are available in summed_ft_data
            if "Summed Imaginary" in self.summed_ft_data and "Summed Real" in self.summed_ft_data:
                # Mix the Magnitude and Phase components
                mixed_ft_data = self.summed_ft_data["Summed Real"] +1j* self.summed_ft_data["Summed Imaginary"]

                # Perform inverse Fourier transform
                mixed_time_domain_data = np.fft.ifft2(np.fft.ifftshift(mixed_ft_data)).real

                # Display the mixed time domain data as an image
                self.display_time_domain_image(mixed_time_domain_data, self.output_1_radioButton.isChecked())
            else:
                print("Error: Magnitude and Phase components are not available for mixing.")  
    
    def extract_region(self):
        self.ft_component_extracted_region = self.original_extracted_region.copy()

        slider_value = self.region_slider.value()

        for image, ft_data in self.ft_component_extracted_region.items():
            if ft_data is not None:
                region = ft_data.copy()

                if self.inner_region_radiobutton.isChecked():
                    region[:100-slider_value, :] = 0
                    region[100+slider_value:, :] = 0
                    region[:, :100-slider_value] = 0
                    region[:, 100+slider_value:] = 0
                else:
                    region[100-slider_value:100+slider_value, 100-slider_value:100+slider_value] = 0

                # Save the inner region in the ft_component_extracted_region dictionary
                self.ft_component_extracted_region[image] = region

                
            
                # Update the FT_component graphics view based on the selected image number
                if image == "Image 1":
                    self.display_ft_component(region, self.FT_component_1)
                elif image == "Image 2":
                    self.display_ft_component(region, self.FT_component_2)
                elif image == "Image 3":
                    self.display_ft_component(region, self.FT_component_3)
                elif image == "Image 4":
                    self.display_ft_component(region, self.FT_component_4)
                        
        print("region", self.ft_component_extracted_region)

    def mix_regions(self):
        if self.Magnitude_phase_radiobutto.isChecked():
            # Check if the Magnitude and Phase components are available in summed_ft_data
            if "Image 1" in self.ft_component_extracted_region and "Image 2" in self.ft_component_extracted_region:
                # Mix the Magnitude and Phase components
                mixed_ft_data = self.ft_component_extracted_region["Image 1"] * np.exp(1j * self.ft_component_extracted_region["Image 2"])

                # Perform inverse Fourier transform
                mixed_time_domain_data = np.fft.ifft2(np.fft.ifftshift(mixed_ft_data)).real

                # Display the mixed time domain data as an image
                self.display_time_domain_image(mixed_time_domain_data, self.output_1_radioButton.isChecked())
            else:
                print("Error: Magnitude and Phase components are not available for mixing.")

    
        # Check if the Magnitude and Phase radio button is checked
        if self.Real_imaginary_radiobutton.isChecked():
            # Check if the Magnitude and Phase components are available in summed_ft_data
            if "Image 3" in self.ft_component_extracted_region and "Image 4" in self.ft_component_extracted_region:
                # Mix the Magnitude and Phase components
                mixed_ft_data = self.ft_component_extracted_region["Image 3"] +1j* self.ft_component_extracted_region["Image 4"]

                # Perform inverse Fourier transform
                mixed_time_domain_data = np.fft.ifft2(np.fft.ifftshift(mixed_ft_data)).real

                # Display the mixed time domain data as an image
                self.display_time_domain_image(mixed_time_domain_data, self.output_1_radioButton.isChecked())
            else:
                print("Error: Magnitude and Phase components are not available for mixing.")   

    def stop_mixing(self):
        self.progressBar.reset()

        self.output_3.setSceneRect(0, 0, 0, 0)
        self.output_3.setScene(QtWidgets.QGraphicsScene())

        self.output_4.setSceneRect(0, 0, 0, 0)
        self.output_4.setScene(QtWidgets.QGraphicsScene())

    def button_clicked(self):
        # Reset the progress bar to its initial state
        self.progressBar.reset()

        # Start the progress bar when regions_mixing_button is clicked
        self.start_progress_bar()

    def start_progress_bar(self):
        # Calculate the number of steps to complete in 1 second with an update every 20 milliseconds
        steps_in_1_second = 1000 / 20
        total_steps = int(steps_in_1_second)
        
        # Set the maximum value of the progress bar
        self.progressBar.setMaximum(total_steps)
        
        # Calculate the update interval to achieve completion in 1 second
        update_interval = int(100 / total_steps)  # Convert to integer

        # Create a QTimer with MainWindow as the parent
        self.progress_timer = QTimer(self.MainWindow)
        self.progress_timer.timeout.connect(self.update_progress)
        
        # Update the progress every calculated interval
        self.progress_timer.start(update_interval)

    def update_progress(self):
        # Get the current value of the progress bar
        current_value = self.progressBar.value()

        # Increment the progress value
        new_value = current_value + 1

        # Update the progress bar value
        self.progressBar.setValue(new_value)

        # Check if the progress bar has reached its maximum value
        if new_value >= self.progressBar.maximum():
            # Stop the progress bar and reset the timer
            self.progress_timer.stop()

    def update_lcd(self, lcd, value):
        lcd.display(value)                     



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
